[tool.poetry]
name = "tidybio"
version = "0.0.1"
description = "Just a simple, tidy Bioinformatics Package for handling sequence data. Not much else to it."
authors = ["JoelP <penaojasjoel870@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "2.0"
matplotlib = "^3.9"
collections = "^1.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
